# Generated by Django 4.2.4 on 2023-08-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mqtt_Logger', '0002_mqttlog2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MqttLog2',
        ),
    ]
